const IMAGES = {
  LABELS: {
    image1: require("../../../public/gallery_images/anitrochepiercing-2.png")
      .default,
    // image2:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/Angelika_Czopek.png")
    //     .default,
    // image3:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image4:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image5:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image6:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image7:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image8:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image9:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image10:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image11:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image12:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image13:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image14:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image15:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image16:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image17:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image18:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image19:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image20:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image21:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image22:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image23:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image24:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image25:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image26:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image27:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image28:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image29:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
    // image30:
    //   require("../../../public/gallery_images/Naklejki_I_etykiety/4_dziary_rabarbary.png")
    //     .default,
  },
};

export default IMAGES;
